name: warp_vpn
description: "Efsane Warp VPN - Liquid Glass Edition"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # İkonlar
  cupertino_icons: ^1.0.8

  # VPN Motoru (Beyin)
  wireguard_flutter: ^0.1.0

  # Liquid Glass Tasarımı (Görsel Şov)
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Eğer arka plana havalı bir görsel eklemek istersen assets klasörü buraya gelecek
  # assets:
  #   - assets/bg.jpg
