name: iOS IPA Build

on:
  push:
    branches: [ main ]

jobs:
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Dependencies
        run: flutter pub get

      - name: iOS Pods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS (no codesign)
        run: flutter build ios --no-codesign

      - name: Create Archive
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ios/build/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: build/ios/ipa/*.ipa
