name: Flutter Build (APK & IPA)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Java Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Clean
        run: flutter clean

      - name: Dependencies
        run: flutter pub get

      - name: iOS Pod Install
        run: |
          cd ios
          pod install
          cd ..

      - name: Android Build (APK)
        run: flutter build apk --debug

      - name: iOS Build (No Codesign)
        run: flutter build ios --no-codesign

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Warp-Build
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/ios/iphoneos/*.app
